// 前端类型统一从 @lowcode/shared 导出（兼容既有 import 路径）
import type {
  ActionNode,
  ActionType,
  ApiBinding,
  ComponentNode,
  EventRule,
  LayerConfig,
  LayerProps,
  LayerType,
  MaterialCategory,
  MaterialContract,
  MaterialInput,
  MaterialItem,
  MaterialKind,
  MaterialManifest,
  MaterialOutput,
  MaterialRef,
  MaterialVersion,
  MaterialVersionMeta,
  OperationLog,
  PageMeta,
  PageSchema
} from '@lowcode/shared';

export type {
  ActionNode,
  ActionType,
  ApiBinding,
  ComponentNode,
  EventRule,
  LayerConfig,
  LayerProps,
  LayerType,
  MaterialCategory,
  MaterialContract,
  MaterialInput,
  MaterialItem,
  MaterialKind,
  MaterialManifest,
  MaterialOutput,
  MaterialRef,
  MaterialVersion,
  MaterialVersionMeta,
  OperationLog,
  PageMeta,
  PageSchema
};
